"""initial schema

All seven tables of blueprint Chapter 12, including every Chapter 13 funnel
timestamp. Autogenerated from app.models and reviewed -- ADR-017.

Revision ID: 0001
Revises:
Create Date: 2026-08-02
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'volunteer', 'admin', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('locations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('victim_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'resolved', 'no_responder_found', name='sos_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_radius_m', sa.Integer(), nullable=False),
    sa.Column('wave_count', sa.Integer(), nullable=False),
    sa.Column('ai_category', sa.String(length=120), nullable=True),
    sa.Column('ai_priority', sa.Enum('low', 'medium', 'high', name='ai_priority', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('ai_status', sa.Enum('ok', 'timeout', 'error', 'skipped', name='ai_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_dispatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('certificate_type', sa.String(length=60), nullable=True),
    sa.Column('skills', sa.Enum('cpr', 'blood_donor', 'first_aid', 'general', name='skill_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dispatch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sos_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('radius_m_at_eval', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('skill_match', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Enum('alerted', 'rejected', name='dispatch_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rejection_reason', sa.Enum('out_of_radius', 'unavailable', 'unverified', 'already_alerted', 'no_socket', name='rejection_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sos_id', sa.Integer(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('final_radius_m', sa.Integer(), nullable=False),
    sa.Column('escalation_trigger', sa.Enum('none', 'empty_set', 'timeout', name='escalation_trigger', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sos_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sos_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'accepted', 'declined', 'dismissed', name='notification_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('notifications')
    op.drop_table('incident_history')
    op.drop_table('dispatch_events')
    op.drop_table('volunteers')
    op.drop_table('sos')
    op.drop_table('locations')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
